### ISSUE TITLE
Annoying Notification Loop

### ISSUE THREAD

**Issue by Rahul5214** [DRAGONMANU/chrome_IIT#1]
When I open chrome, notification for Moodle and Webmail appears on right lower corner of the screen and when I click on the "cross" in the notification to close it, it comes again after some time(usually 5 seconds). This happens again and again until I click on the notification. These repetitive notifications are annoying. Please take a look in this issue. 
Great work by the way

**Comment by DRAGONMANU** [comment]
Please use the updated extension ^ ^. Fixed the loop.
